### ISSUE TITLE
Plugin tool bar does not show on QGIS 3.20

### ISSUE THREAD

**Issue by picaosgeo** [tmizu23/bezierEditing#15]
If I use QGIS plugin management in QGIS3.20 to install a plugin from the uninstalled list, BezierEditing toolbar does not appear. 
If I copy BezierEditing folder directly into the plugins folder and then start QGIS, BezierEditing toolbar appears.

**Comment by tmizu23** [comment]
I tried deleting the following configuration file containing the plugin and then installing the BezierEditing plugin from the uninstalled list, and it showed up fine in the toolbar.
C:\Users\xxxxxx\AppData\Roaming\QGIS\QGIS3

My test version is QGIS 3.20.3 and 3.22.0 on Windows

Hmmm...what could be the cause?
