### ISSUE TITLE
"Reuse last entered attribute values" not working

### ISSUE THREAD

**Issue by slivalubo** [tmizu23/bezierEditing#18]
Checked option "Reuse last entered attribute values" (QGIS 3.22/Settings / Options / Digitizing) does not work in the attribute pop-up window after line/polygon feature digitizing is completed.

**Comment by tmizu23** [comment]
It seems to be a feature of QGIS version 3.20 or later, so I will consider implementing it after a while for compatibility with earlier versions.

https://github.com/qgis/QGIS/blob/c8156b01066107b91121417e423dee4a299affc3/src/core/editform/qgseditformconfig.h#L239-L246

thank you

**Comment by slivalubo** [comment]
Thank you, BezierEditing is perfect tool, I use it for digitizing countour lines.

**Comment by tmizu23** [comment]
Now supported in Version 1.3.5
