### ISSUE TITLE
Unnamed UI Element

### ISSUE THREAD

**Issue by TNogatz** [tmizu23/BezierEditing#2]
Hello,
starting QGIS with BezierEditing installed > immediately appears an error window saying "Unnamed UI element. (dtype_uielement)". 
Environment: QGIS 3.4.11, Windows 10
Best wishes, Thomas

**Comment by tmizu23** [comment]
I tried it in the same environment QGIS 3.4.11, Windows 10 but it was no problem.
I have no idea for the error.

**Comment by AlisterH** [comment]
Hi Thomas, it seems this warning is produced by the "QGIST Workbench" plugin, if you have the setting "Warn if UI elements can not be uniquely identified".  In my case I don't have the bezier editing plugin, but maybe it and another plugin share a problem...

The only plugin that actually contains the string "dtype_uielement" is actually QGIST itself, so I'm not sure if it is warning about itself, or just being cryptic when warning about something else.
