### ISSUE TITLE
initGui() method Failing

### ISSUE THREAD

**Issue by debboutr** [tmizu23/bezierEditing#25]
I fixed this by just changing the `0.5` to `1` on line 60 of the `beziereditingtool.py` file. I'm guessing this method just changed it's argument requirement??? Seems like this is the only place that `setWidth` is called without an `int` in the argument. Thanks for all the work on this package!

![image](https://user-images.githubusercontent.com/7052993/170193479-f256839b-6d00-4582-a46d-3450566f143c.png)

**Comment by tmizu23** [comment]
Thanks for the report.
Is the OS linux?
