### ISSUE TITLE
QGIS Snapping not obeyed by BezierEditing

### ISSUE THREAD

**Issue by fgfletcher** [tmizu23/bezierEditing#26]
With QGIS snapping enabled with a point layer selected as the snapping source
 when using the add vertex tool on another layer the cursor snaps to nearest point if one is within range
 however, BezierEditing does not snap, instead it acts as if snapping was not enabled
Snapping is very useful when drawing networks.  It would be great if BezierEditing supported it.
Thanks for a wonderful plugin!

**Comment by tmizu23** [comment]
Thanks for your comment, 
BezierEditing already supports the snapping feature. With snapping enabled, when you approach a point with the Bezier tool, a blue frame will appear and snap.
I am not sure what the cause is, but could you please check your settings?

**Comment by fgfletcher** [comment]
My apologies!
It turned out that in QGIS'  Project > Snapping Options >  I had failed to change the type to "Vertex".  It had defaulted to "Centroid".
Once I corrected the type it snapped perfectly.
My thanks for your wonderful and much appreciated plugin!
