### ISSUE TITLE
Plugin ignores suppress attributes dialog setting

### ISSUE THREAD

**Issue by chateauferret** [tmizu23/bezierEditing#37]
When I create or edit a feature the attributes dialog appears, even if suppression of this dialog is set in QGIS settings. Possibly a new issue in QGIS 3.30.2 'sHertogenbosch, because I don't seem to remember this happening before upgrading to that verson.

**Comment by tmizu23** [comment]
Thank you for your report. I have confirmed the issue. I will attempt to fix it.

**Comment by tmizu23** [comment]
Now fixed in Version 1.3.7
