### ISSUE TITLE
Are the main buttons working as intended?

### ISSUE THREAD

**Issue by AlisterH** [tmizu23/bezierEditing#38]
I don't think the two main buttons are working properly (Bezier edit and edit bezier freehand).
If I click them both they both stay on, and the only way to deactivate them is to activate some other QGIS tool instead.
Surely the intended behaviour is either that clicking one deactivates the other, or that on or both of them can be toggled off by clicking on it? 
I am in QGIS 3.34.1

**Comment by tmizu23** [comment]
Thank you for your report. I have confirmed the issue. I will attempt to fix it.

**Comment by tmizu23** [comment]
Now fixed in Version 1.3.7
